### ISSUE TITLE
MDX files using .PDX sample banks don't play properly

### ISSUE THREAD

**Issue by freq-mod** [gzaffin/mdxmini#1]
...as PCM is silent.
[mdxsamples.zip](https://github.com/gzaffin/mdxmini/files/7877814/mdxsamples.zip) - examples of such files
 
EDIT: it's the case with files utilizing PCM8 sub-driver, normal MDX+PDX music works fine

**Comment by gzaffin** [comment]
I tried to help .PDX loading leveraging .MDX file path and with backup /.mdxplay/ folder. There also -q option safety belt.
Please let me know.

**Comment by gzaffin** [comment]
I'm trying to double check EX-PCM/PCM8 P-W channels while replaying Your mdxsample mdx modules taking X68Sound like reference.
